# Generated by Django 3.1.7 on 2021-04-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('meaning', models.CharField(max_length=200)),
                ('synonyms', models.CharField(max_length=200)),
                ('antonyms', models.CharField(max_length=200)),
                ('usage', models.CharField(max_length=300)),
                ('date', models.DateField()),
            ],
        ),
    ]
