# Generated by Django 3.1.7 on 2021-04-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaryapp', '0004_auto_20210406_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
